import type { TTraining } from '@/context/TrainingContext';

export const INSTRUMENTS = {
  eguitar: 'Электрогитара',
  acguitar: 'Акустическая гитара',
  bass: 'Бас-гитара',
  piano: 'Пианино',
  drums: 'Барабаны',
  vocal: 'Вокал',
  other: 'Другие инструменты',
};

export const EXERCISE_TYPES = {
  improvisation: 'Импровизация',
  exercises: 'Упражнения',
  theory: 'Теория',
  songs: 'Песни',
  recording: 'Запись',
  rhythm: 'Ритм',
};

export const mockData: { tableData: TTraining[]; stats: any } = {
  tableData: [
    {
      id: '1',
      name: 'Импро и упражнения',
      description: 'Закрепил упражения на гаммы и импровизацию в стиле блюз',
      date: '01.12.2025',
      type: ['improvisation', 'exercises'],
      difficulty: 3,
      instrument: 'eguitar',
      timer: 30,
    },
    {
      id: '2',
      name: 'Теория и анализ',
      description: 'Изучил теорию аккордов и их применение в импровизации',
      date: '02.11.2025',
      type: ['theory'],
      difficulty: 2,
      instrument: 'piano',
      timer: 900,
    },
    {
      id: '3',
      name: 'Песня "Sweet Child O\' Mine"',
      description: "Отработал соло и ритм-гитару для песни Guns N' Roses",
      date: '03.09.2025',
      type: ['songs'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: 12600,
    },
    {
      id: '4',
      name: 'Запись и сведение',
      description: 'Записал и свел трек с использованием эффектов и панорамирования',
      date: '04.05.2025',
      type: ['recording'],
      difficulty: 5,
      instrument: 'other',
      timer: 7800,
    },
    {
      id: '5',
      name: 'Ритмика и метр',
      description: 'Отработал ритмические паттерны и метр для барабанов',
      date: '05.12.2024',
      type: ['rhythm'],
      difficulty: 3,
      instrument: 'drums',
      timer: 300,
    },
    {
      id: '6',
      name: 'Импровизация на блюзовой основе',
      description: 'Импровизировал на блюзовой основе с использованием различных ликов',
      date: '06.10.2024',
      type: ['improvisation'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: 769,
    },
    {
      id: '7',
      name: 'Вокализы и песни',
      description: 'Отработал вокализы и песни с использованием различных техник',
      date: '07.04.2024',
      type: ['songs', 'exercises'],
      difficulty: 2,
      instrument: 'vocal',
      timer: 100000,
    },
    {
      id: '8',
      name: 'Анализ песни "Hotel California"',
      description: 'Проанализировал структуру и гармонию песни Eagles',
      date: '08.03.2024',
      type: ['theory'],
      difficulty: 3,
      instrument: 'acguitar',
      timer: 7,
    },
    {
      id: '9',
      name: 'Запись демо-трека',
      description: 'Записал демо-трек с использованием нескольких инструментов',
      date: '09.01.2024',
      type: ['recording'],
      difficulty: 5,
      instrument: 'other',
      timer: 14,
    },
  ],
  stats: {
    alltime: 121820, // сумма timer
    timeTrainings: [
      { date: '01.12.2025', time: 7800 },
      { date: '02.11.2025', time: 900 },
      { date: '03.09.2025', time: 12600 },
      { date: '04.05.2025', time: 7800 },
      { date: '05.12.2024', time: 300 },
      { date: '06.10.2024', time: 769 },
      { date: '07.04.2024', time: 2000 },
      { date: '08.03.2024', time: 7 },
      { date: '09.01.2024', time: 14 },
    ],
    difficulty: { 1: 0, 2: 2, 3: 3, 4: 2, 5: 2 },
    trainTypes: {
      improvisation: 5,
      exercises: 2,
      theory: 0,
      songs: 4,
      recording: 3,
      rhythm: 1,
    },
  },
};
