export const INSTRUMENTS = {
  eguitar: 'Электрогитара',
  acguitar: 'Акустическая гитара',
  bass: 'Бас-гитара',
  piano: 'Пианино',
  drums: 'Барабаны',
  vocal: 'Вокал',
  other: 'Другие инструменты',
};

export const EXERCISE_TYPES = {
  improvisation: 'Импровизация',
  exercises: 'Упражнения',
  theory: 'Теория/Анализ',
  songs: 'Песни',
  recording: 'Запись/Сведение',
  rhythm: 'Ритм',
};

export const mockData = {
  tableData: [
    {
      id: 1,
      name: 'Импро и упражнения',
      description: 'Закрепил упражения на гаммы и импровизацию в стиле блюз',
      date: '01.12.2025',
      type: ['improvisation', 'exercises'],
      difficulty: 3,
      instrument: 'eguitar',
      timer: '00:00:30',
    },
    {
      id: 2,
      name: 'Теория и анализ',
      description: 'Изучил теорию аккордов и их применение в импровизации',
      date: '02.11.2025',
      type: ['theory'],
      difficulty: 2,
      instrument: 'piano',
      timer: '00:01:00',
    },
    {
      id: 3,
      name: 'Песня "Sweet Child O\' Mine"',
      description: "Отработал соло и ритм-гитару для песни Guns N' Roses",
      date: '03.09.2025',
      type: ['songs'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: '00:02:00',
    },
    {
      id: 4,
      name: 'Запись и сведение',
      description: 'Записал и свел трек с использованием эффектов и панорамирования',
      date: '04.05.2025',
      type: ['recording'],
      difficulty: 5,
      instrument: 'other',
      timer: '00:03:00',
    },
    {
      id: 5,
      name: 'Ритмика и метр',
      description: 'Отработал ритмические паттерны и метр для барабанов',
      date: '05.12.2024',
      type: ['rhythm'],
      difficulty: 3,
      instrument: 'drums',
      timer: '00:01:30',
    },
    {
      id: 6,
      name: 'Импровизация на блюзовой основе',
      description: 'Импровизировал на блюзовой основе с использованием различных ликов',
      date: '06.10.2024',
      type: ['improvisation'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: '00:02:30',
    },
    {
      id: 7,
      name: 'Вокализы и песни',
      description: 'Отработал вокализы и песни с использованием различных техник',
      date: '07.04.2024',
      type: ['songs', 'exercises'],
      difficulty: 2,
      instrument: 'vocal',
      timer: '00:01:15',
    },
    {
      id: 8,
      name: 'Анализ песни "Hotel California"',
      description: 'Проанализировал структуру и гармонию песни Eagles',
      date: '08.03.2024',
      type: ['theory'],
      difficulty: 3,
      instrument: 'acguitar',
      timer: '00:02:00',
    },
    {
      id: 9,
      name: 'Запись демо-трека',
      description: 'Записал демо-трек с использованием нескольких инструментов',
      date: '09.01.2024',
      type: ['recording'],
      difficulty: 5,
      instrument: 'other',
      timer: '00:04:00',
    },
  ],
};
