import type { TTraining } from '@/context/TrainingContext';

export const INSTRUMENTS = {
  eguitar: 'Электрогитара',
  acguitar: 'Акустическая гитара',
  bass: 'Бас-гитара',
  piano: 'Пианино',
  drums: 'Барабаны',
  vocal: 'Вокал',
  other: 'Другие инструменты',
};

export const EXERCISE_TYPES = {
  improvisation: 'Импровизация',
  exercises: 'Упражнения',
  theory: 'Теория',
  songs: 'Песни',
  recording: 'Запись',
  rhythm: 'Ритм',
};

export const mockData: { tableData: TTraining[]; stats: any } = {
  tableData: [
    {
      id: '1',
      name: 'Импро и упражнения',
      description: 'Закрепил упражения на гаммы и импровизацию в стиле блюз',
      date: '2025-05-20T21:00:00.000Z',
      type: ['improvisation', 'exercises'],
      difficulty: 3,
      instrument: 'eguitar',
      timer: 730,
    },
    {
      id: '2',
      name: 'Теория и анализ',
      description: 'Изучил теорию аккордов и их применение в импровизации',
      date: '2025-04-23T21:00:00.000Z',
      type: ['theory', 'exercises', 'recording', 'improvisation'],
      difficulty: 2,
      instrument: 'piano',
      timer: 900,
    },
    {
      id: '3',
      name: 'Песня "Sweet Child O\' Mine"',
      description: "Отработал соло и ритм-гитару для песни Guns N' Roses",
      date: '2025-04-19T21:00:00.000Z',
      type: ['songs', 'exercises'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: 1600,
    },
    {
      id: '4',
      name: 'Запись и сведение',
      description: 'Записал и свел трек с использованием эффектов и панорамирования',
      date: '2025-03-25T21:00:00.000Z',
      type: ['recording', 'exercises'],
      difficulty: 5,
      instrument: 'other',
      timer: 7800,
    },
    {
      id: '5',
      name: 'Ритмика и метр',
      description: 'Отработал ритмические паттерны и метр для барабанов',
      date: '2025-03-09T21:00:00.000Z',
      type: ['rhythm'],
      difficulty: 3,
      instrument: 'drums',
      timer: 300,
    },
    {
      id: '6',
      name: 'Импровизация на блюзовой основе',
      description: 'Импровизировал на блюзовой основе с использованием различных ликов',
      date: '2025-03-08T21:00:00.000Z',
      type: ['improvisation', 'exercises'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: 1769,
    },
    {
      id: '7',
      name: 'Вокализы и песни',
      description: 'Отработал вокализы и песни с использованием различных техник',
      date: '2025-02-18T21:00:00.000Z',
      type: ['songs', 'exercises'],
      difficulty: 2,
      instrument: 'vocal',
      timer: 380,
    },
    {
      id: '8',
      name: 'Анализ песни "Hotel California"',
      description: 'Проанализировал структуру и гармонию песни Eagles',
      date: '2025-01-11T21:00:00.000Z',
      type: ['theory'],
      difficulty: 3,
      instrument: 'acguitar',
      timer: 923,
    },
    {
      id: '9',
      name: 'Запись демо-трека',
      description: 'Записал демо-трек с использованием нескольких инструментов',
      date: '2025-01-01T21:00:00.000Z',
      type: ['recording', 'exercises'],
      difficulty: 5,
      instrument: 'other',
      timer: 600,
    },
    {
      id: '10',
      name: 'Теория ритма',
      description: 'Изучил основы ритмики и метронома',
      date: '2024-12-15T21:00:00.000Z',
      type: ['theory', 'rhythm'],
      difficulty: 2,
      instrument: 'drums',
      timer: 450,
    },
    {
      id: '11',
      name: 'Импровизация на фортепиано',
      description: 'Практиковал импровизацию в джазовом стиле',
      date: '2024-12-01T21:00:00.000Z',
      type: ['improvisation'],
      difficulty: 3,
      instrument: 'piano',
      timer: 800,
    },
    {
      id: '12',
      name: 'Запись вокала',
      description: 'Записал вокальные партии для новой композиции',
      date: '2024-11-20T21:00:00.000Z',
      type: ['recording', 'songs'],
      difficulty: 4,
      instrument: 'vocal',
      timer: 1200,
    },
    {
      id: '13',
      name: 'Теория гармонии',
      description: 'Изучил гармонические последовательности',
      date: '2024-11-10T21:00:00.000Z',
      type: ['theory'],
      difficulty: 3,
      instrument: 'piano',
      timer: 600,
    },
    {
      id: '14',
      name: 'Упражнения на скорость',
      description: 'Тренировал скорость игры на гитаре',
      date: '2024-10-25T21:00:00.000Z',
      type: ['exercises'],
      difficulty: 4,
      instrument: 'eguitar',
      timer: 950,
    },
    {
      id: '15',
      name: 'Разбор песни "Yesterday"',
      description: 'Разобрал аккорды и мелодию песни Beatles',
      date: '2024-10-10T21:00:00.000Z',
      type: ['songs', 'theory'],
      difficulty: 2,
      instrument: 'acguitar',
      timer: 700,
    },
    {
      id: '16',
      name: 'Ритмические упражнения',
      description: 'Практиковал сложные ритмические рисунки',
      date: '2024-09-30T21:00:00.000Z',
      type: ['rhythm', 'exercises'],
      difficulty: 3,
      instrument: 'drums',
      timer: 500,
    },
    {
      id: '17',
      name: 'Импровизация с группой',
      description: 'Совместная импровизация с другими музыкантами',
      date: '2024-09-15T21:00:00.000Z',
      type: ['improvisation', 'exercises'],
      difficulty: 5,
      instrument: 'eguitar',
      timer: 1800,
    },
    {
      id: '18',
      name: 'Запись инструментала',
      description: 'Записал инструментальную партию для проекта',
      date: '2024-09-01T21:00:00.000Z',
      type: ['recording'],
      difficulty: 4,
      instrument: 'other',
      timer: 1100,
    },
    {
      id: '19',
      name: 'Упражнения на аккорды',
      description: 'Тренировал смену аккордов и баррэ',
      date: '2024-08-20T21:00:00.000Z',
      type: ['exercises'],
      difficulty: 2,
      instrument: 'acguitar',
      timer: 650,
    },
  ],
  stats: {
    alltime: 130570,
    trainTypes: {
      improvisation: 5,
      exercises: 11,
      theory: 5,
      songs: 4,
      recording: 5,
      rhythm: 3,
    },
  },
};
